### ISSUE TITLE
Error while loading Knights of Terrafirma: NoSuchFieldError: enableKnightArmor

### ISSUE THREAD

**Issue by Souttak** [WitchkingsRu/KnightsOfTerraFirma#1]
I get this error when loading my 1.20.1 Minecraft instance with both `Epic Knights` and `Knights of Terrafirma`:

![image](https://github.com/user-attachments/assets/6d718c5d-4807-4fec-9704-2a859933c467)

Here's the full crash log:
[crash-2024-10-12_15.49.53-fml.txt](https://github.com/user-attachments/files/17351152/crash-2024-10-12_15.49.53-fml.txt)

If you need help with anything just tell me! I have never done a Minecraft mod but I'm a programmer too, and I really want to use your mod in my pack!

Thanks for your help.

**Comment by WitchkingsRu** [comment]
Hi there! That's a known issue and fix is well on the way. If you want to play with my mod right now, you should use Epic Knights 9.8.
